import { findInfographic } from '~/data/infographics'

/**
 * BF-224: link-preview meta (Open Graph + Twitter) for an infographic.
 *
 * Link previews in LinkedIn/Bluesky/Slack — and Squarespace's URL embed, which
 * reported "no embeddable content found" — read these tags; before this, no
 * page carried any. The image is the 1200×630 teaser generated by
 * scripts/export-thumbnails.mjs into public/thumbnails/.
 *
 * Crawlers need absolute URLs, so they are built from `siteUrl` (Netlify's
 * `URL` at build time, falling back to the production origin).
 */
export function useInfographicSeo(slug: string) {
  const entry = findInfographic(slug)
  if (!entry) return

  const { siteUrl } = useRuntimeConfig().public
  const route = useRoute()
  const title = entry.cover?.headline ?? entry.title

  useSeoMeta({
    description: entry.description,
    ogTitle: title,
    ogDescription: entry.description,
    ogType: 'website',
    ogSiteName: 'Bertelsmann Foundation — Indo-Pacific',
    ogUrl: `${siteUrl}/infographics/${slug}`,
    ogImage: `${siteUrl}/thumbnails/${slug}-og.jpg`,
    ogImageWidth: 1200,
    ogImageHeight: 630,
    ogImageAlt: title,
    twitterCard: 'summary_large_image',
    twitterTitle: title,
    twitterDescription: entry.description,
    twitterImage: `${siteUrl}/thumbnails/${slug}-og.jpg`
  })

  // Squarespace/Embedly and other consumers resolve relative links against this.
  useHead({
    link: [{ rel: 'canonical', href: `${siteUrl}${route.path.startsWith('/embed/') ? `/infographics/${slug}` : route.path}` }]
  })
}
